### ISSUE TITLE
Cannot install on newer React versions

### ISSUE THREAD

**Issue by nicollegah** [hugozap/react-rotary-knob#54]
Hey, these knobs look amazing and I would love to use them in a project of mine (and weirdly, there don't seem to be lots of react knobs out there). 

However I can't install on React >18

!npm install react-rotary-knob

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: frontend@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-rotary-knob@1.1.8
npm ERR! node_modules/react-rotary-knob
npm ERR!   react-rotary-knob@"*" from the root project

Is there anything I can do?

**Comment by hugozap** [comment]
Hey @nicollegah I updated the component to work with React Versions 18.2+ Should work now.

**Comment by nicollegah** [comment]
Oh wow, thanks for this. Unfortunately I have still the same problem.

(base) ➜  frontend git:(main) ✗ npm i react-rotary-knob
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: nf-frontend@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-rotary-knob@3.0.0
npm ERR! node_modules/react-rotary-knob
npm ERR!   react-rotary-knob@"^3.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by hugozap** [comment]
Can you try deleting node_modules, and the package .lock file and running
nom install again?
Otherwise could you share more about your setup to try to reproduce the
issue?

**Comment by nicollegah** [comment]
Same thing unfortunately. I am getting the same problem with a completely new project (create-t3-app).

```
(base) ➜  coding npm create t3-app@latest
Need to install the following packages:
  create-t3-app@7.7.0
Ok to proceed? (y) y
   ___ ___ ___   __ _____ ___   _____ ____    __   ___ ___
  / __| _ \ __| /  \_   _| __| |_   _|__ /   /  \ | _ \ _ \
 | (__|   / _| / /\ \| | | _|    | |  |_ \  / /\ \|  _/  _/
  \___|_|_\___|_/‾‾\_\_| |___|   |_| |___/ /_/‾‾\_\_| |_|


? What will your project be called? testing
? Will you be using TypeScript or JavaScript? TypeScript
Good choice! Using TypeScript!
? Which packages would you like to enable?
? Initialize a new git repository? No
Sounds good! You can come back and run git init later.
? Would you like us to run 'npm install'? Yes
Alright. We'll install the dependencies for you!
? What import alias would you like configured? ~/

Using: npm

✔ testing scaffolded successfully!

Adding boilerplate...
✔ Successfully setup boilerplate for envVariables

Installing dependencies...
✔ Successfully installed dependencies!

Next steps:
  cd testing
  npm run dev
(base) ➜  coding cd testing
(base) ➜  testing npm install react-rotary-knob
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: testing@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.0" from react-rotary-knob@3.0.0
npm ERR! node_modules/react-rotary-knob
npm ERR!   react-rotary-knob@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /Users/klemkeni/.npm/_logs/2023-03-12T11_33_51_069Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/klemkeni/.npm/_logs/2023-03-12T11_33_51_069Z-debug-0.log
```


In that case, package.json looks like this
`<html><head></head><body>

name | "testing"
-- | --
version | "0.1.0"
private | true
scripts |  
dev | "next dev"
build | "next build"
start | "next start"
lint | "next lint"
dependencies |  
next | "^13.2.1"
react | "18.2.0"
react-dom | "18.2.0"
zod | "^3.20.6"
devDependencies |  
@types/node | "^18.14.0"
@types/react | "^18.0.28"
@types/react-dom | "^18.0.11"
@types/eslint | "^8.21.1"
@typescript-eslint/eslint-plugin | "^5.53.0"
@typescript-eslint/parser | "^5.53.0"
eslint | "^8.34.0"
eslint-config-next | "^13.2.1"
typescript | "^4.9.5"
ct3aMetadata |  
initVersion | "7.7.0"

</body></html>`


I also did the same with npx create-react-app and am getting the same problem.

MacOS Ventura 13.2.1  🙁

**Comment by hugozap** [comment]
I haven't tested with t3 but latest version updates the peer dependency to react. Could you please try again?

**Comment by nicollegah** [comment]
Sorry for the late reply, I was a bit off the grid. It works now. Thank you so, so much! ❤️

**Comment by cordial** [comment]
any chance this can be updated to work with React 19?
